# Import the Relevant libraries

In [1]:
import numpy as np

Declare scalars, vectors and matrices

# Scalar

In [3]:
s = 5

In [4]:
s

5


# Vectors

In [5]:
v = np.array([5,-2,4])

In [6]:
v

array([ 5, -2,  4])

# Matrices

In [7]:
m = np.array([[5,12,6],[-3,0,14]])

In [8]:
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

# Data Types

In [9]:
type(s)

int

In [10]:
type(v)

numpy.ndarray

In [11]:
type(m)

numpy.ndarray

# Convert S into an Array

In [12]:
s

5

In [13]:
s_array = np.array(s)

In [14]:
s_array

array(5)


# Data Shape

In [15]:
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [16]:
m.shape

(2, 3)

In [17]:
v

array([ 5, -2,  4])

In [18]:
v.shape

(3,)

In [19]:
v.reshape(1,3)

array([[ 5, -2,  4]])

In [20]:
v.reshape(3,1)

array([[ 5],
       [-2],
       [ 4]])

In [21]:
s_array.shape

()

# Tensor Creation 

In [22]:
m1 = np.array([[5,12,6],[-3,0,14]])
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [30]:



m2 = np.array([[9,8,7],[1,3,-5]])
m2

array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [24]:
t = np.array([m1,m2])

In [25]:
t

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

In [26]:
t.shape

(2, 2, 3)

In [27]:
t_manual = np.array([ [[5,12,6],[-3,0,14]],[[9,8,7],[1,3,-5]] ]) 

In [28]:
t_manual 

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

In [29]:
m1 + 1

array([[ 6, 13,  7],
       [-2,  1, 15]])

# Transpose

In [31]:
A = np.array([[9,8,7],[1,3,-5]])
A

array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [32]:
A.T

array([[ 9,  1],
       [ 8,  3],
       [ 7, -5]])

# Dot Product 

In [33]:
v

array([ 5, -2,  4])

In [34]:
x = np.array([3,4,5])

In [35]:
x

array([3, 4, 5])

In [36]:
np.dot(v,x)

27