In [1]:
import numpy as np
import sklearn.model_selection import train_test_split 

SyntaxError: invalid syntax (<ipython-input-1-6e277d06662a>, line 2)

In [2]:
import numpy as np
from sklearn.model_selection import train_test_split 

In [3]:
a = np.arange(1,101)

In [4]:
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [5]:
b = np.arange(501,600)

In [6]:
b

array([501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513,
       514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526,
       527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539,
       540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552,
       553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565,
       566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578,
       579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591,
       592, 593, 594, 595, 596, 597, 598, 599])

In [7]:
train_test_split(a)

[array([ 71,   4,  25,  37,  22,  28,   9,  17,  87,  33,  68,  97,  19,
        100,  43,  60,  27,  75,  47,  42,  41,  32,  26,  38,  70,  69,
         51,  39,  13,  30,  18,  65,  86,  61,  40,  66,  48,  49,   3,
         34,  72,  56,  50,  92,  78,   5,  57,  53,  55,  89,  83,  77,
         59,  46,  67,  11,  95,  93,  76,  36,  98,  94,  21,  44,  80,
          7,  81,  91,  84,   6,  73,  62,  54,  20,  99]),
 array([15, 85, 35, 64, 63, 10, 58,  1, 74, 79, 31, 16, 96, 24, 23, 52, 45,
        90, 82, 88, 29, 12, 14,  2,  8])]

In [8]:
a_train,a_test = train_test_split(a)

In [9]:
a_train.shape, a_test.shape

((75,), (25,))

In [10]:
a_train

array([ 22,  53,  84,  98,  39,  64,  80,  65,  81,  35,  61,  73,  83,
        87,  72,  76,  68,  92,  38,  30,  93,  96,  10,  11,  75,  27,
        43,  50,  18,  89,  70,  12,  85,   2,  58,  45,  51,  63,  82,
         6,  15, 100,  44,  94,  62,   9,  88,  41,  19,  20,  40,  42,
         7,  97,  78,  90,  13,  49,  32,   8,  79,  25,  60,  56,  37,
         5,  48,  54,  34,  23,  69,  74,  28,  71,  14])

In [11]:
a_test

array([66, 29, 55, 59,  4,  3, 47, 33,  1, 52, 36, 99, 17, 31, 24, 57, 46,
       91, 77, 16, 95, 21, 86, 67, 26])

In [12]:
a_train,a_test = train_test_split(a, test_size = 0.2)


In [13]:
a_train.shape, a_test.shape

((80,), (20,))

In [14]:
a_train,a_test = train_test_split(a, test_size = 0.2, shuffle = false)

NameError: name 'false' is not defined

In [15]:
a_train,a_test = train_test_split(a, test_size = 0.2, shuffle = False)

In [16]:
a_train.shape, a_test.shape

((80,), (20,))

In [17]:
a_train,a_test = train_test_split(a, test_size = 0.2, shuffle = Test)

NameError: name 'Test' is not defined

In [18]:
a_train,a_test = train_test_split(a, test_size = 0.2, shuffle = True)

In [19]:
a_train,a_test = train_test_split(a, test_size = 0.2, shuffle = True, random_state=42)

In [20]:
a_train,a_test,b_train,b_test = train_test_split(a,b test_size = 0.2,random_state=42 )

SyntaxError: invalid syntax (<ipython-input-20-a51c0caeb1c5>, line 1)

In [21]:
a_train,a_test,b_train,b_test = train_test_split(a,b,test_size = 0.2,random_state=365 )

ValueError: Found input variables with inconsistent numbers of samples: [100, 99]

In [22]:
a_train,a_test,b_train,b_test = train_test_split(a,b,test_size = 0.2,random_state=365 )

ValueError: Found input variables with inconsistent numbers of samples: [100, 99]

In [23]:
a_train, a_test, b_train, b_test = train_test_split(a, b, test_size = 0.2, random_state=365 ) 

ValueError: Found input variables with inconsistent numbers of samples: [100, 99]